services:
  db:
    platform: linux/arm64
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
    command: ["sh", "-c", "sleep 20 && /entrypoint.sh mysqld"]
